spring.application.name=hrms-system

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DATABSE_URL}
spring.datasource.username=${DATABSE_USERNAME}
spring.datasource.password=${DATABSE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# ===============================
# SERVER
# ===============================
server.port=${PORT:8090}


# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.hrms.hrms_system=INFO
